apiVersion: apps/v1
kind: Deployment
metadata:
  name: meuprimeirodeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: site
        image: galladas/kube-news:{{TAG}}